### PR TITLE
Add Zuul installation guide

### PR DESCRIPTION
**Pull request by osfrickler**
Since the successful installation of a Zuul deployment is a bit more complicated than simply applying the service role, we document it in a dedicated chapter of the documentation.

### CODE REVIEW

**Comment by ra-beer** [comment]
For publishing in docusaurus and within the scs documentation, we need to rebuild the documentation. Files must be markdown and structure must fitting to this guide: https://github.com/SovereignCloudStack/docs/blob/main/community/contribute/adding-docs-guide.md

**Comment by osfrickler** [comment]
Can the rebuild be done in a second step? Currently everything is still in rst afaict.

**Comment by berendt** [comment]
I think it's fine to keep RST/Sphinx here for the moment. This is the reference documentation of the roles which is independent of the SCS documentation.

**Comment by berendt** [comment]
We will test it with Benjamin with the SCS Zuul and in the TSI project.

**Pull request merged**
